### ISSUE TITLE
Add logic to handle 'hoard' action card

### ISSUE THREAD

**Issue by tigerclaw-az** [ejwaibel/squarrels#3]
When the player draws a "Hoard" card, the following actions must take place:

1. Show blank card and slowly rotate until card is fully visible
2. After card has completed rotation, allow player to click on the Hoard Deck

**Comment by ejwaibel** [comment]
1. When 'Hoard' card is drawn, show blank card and slowly rotate until card is fully visible
2. After card has completed rotation, allow player to click on the Hoard Deck
